name: Devhutch CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devhutch-server:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/devhutch-server:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{secrets.DOCKER_USERNAME}}/devhutch-server:latest
            sudo docker stop devhutch-server-container || true
            sudo docker rm devhutch-server-container || true
            sudo docker run -v /home/ec2-user/secrets/FirebaseService.json:${{secrets.GOOGLE_APPLICATION_CREDENTIALS_PATH}} -d --name devhutch-server-container -e PORT=${{secrets.PORT}} -e NODE_ENV=production  -e CLIENT_URL=${{secrets.CLIENT_URL}} -e MONGO_URI=${{secrets.MONGO_URI}} -e GOOGLE_APPLICATION_CREDENTIALS=${{secrets.GOOGLE_APPLICATION_CREDENTIALS_PATH}} -e RECAPTCHA_SITE_SECRET=${{secrets.RECAPTCHA_SITE_SECRET}} -p 5000:5000 ${{secrets.DOCKER_USERNAME}}/devhutch-server:latest
